In [1]:
import numpy as np

In [2]:
sales = np.array([[6, 9, 8],
                 [57, 0, 64],
                 [63, 12, 1056]])

sales

array([[   6,    9,    8],
       [  57,    0,   64],
       [  63,   12, 1056]])

In [3]:
#sum() - it return the sum of the elements of array
sales.sum()

1275

In [5]:
#mean() - it returns the average value of sum of array
sales.mean().round(2)

141.67

In [6]:
#max - return the max number of elements from an array
sales.max()

1056

In [8]:
#min - returns the smallest nos of the matrics
sales.min()

0

In [9]:
#Aggregation across rows & columns

sales

array([[   6,    9,    8],
       [  57,    0,   64],
       [  63,   12, 1056]])

In [10]:
sales.sum()

1275

In [11]:
#Aggregate across columns
sales.sum(axis = 1)

array([  23,  121, 1131])

In [12]:
#Aggregate Accross the rows
sales.sum(axis = 0)

array([ 126,   21, 1128])

In [14]:
#numpy.sum: compute the sum of array elements
import numpy as np

a = np.array([[13,14, 15], [16, 17, 18]])

#Sum of all elements in the array
total = np.sum(a)

total

93

In [16]:
#Sum along a specific axis (1 = rows, 0 = columns)
sumofColumns = np.sum(a, axis=0)
sumofColumns

array([29, 31, 33])

In [18]:
sumofRows = np.sum(a, axis = 1)
sumofRows

array([42, 51])

In [19]:
# numpy.mean: compute the mean (average) of array elements
x = np.array([[1,2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [20]:
#average
np.mean(x)

2.5

In [23]:
#mean by column
np.mean(x, axis = 0, dtype = int)

array([2, 3])

In [24]:
#mean by row
np.mean(x, axis = 1)

array([1.5, 3.5])

In [25]:
#numpy.min & numpy.max: compute the minimum & maximum no of array element
y = np.array([[6, 9, 8],
             [16, 12, 28],
             [13, 12, 21]])
y

array([[ 6,  9,  8],
       [16, 12, 28],
       [13, 12, 21]])

In [27]:
#min no of an array
np.min(y)

6

In [28]:
np.min(y, axis = 0)

array([6, 9, 8])

In [29]:
np.min(y, axis = 1)

array([ 6, 12, 12])

In [30]:
np.max(y)

28

In [31]:
np.max(y, axis = 0)

array([16, 12, 28])

In [32]:
np.max(y, axis = 1)

array([ 9, 28, 21])

In [34]:
#compute the median of an array elements
np.median(y)

12.0

In [35]:
np.median(y, axis = 0)

array([13., 12., 21.])

In [36]:
np.median(y, axis = 1)

array([ 8., 16., 13.])

In [38]:
#Percentile
sales

array([[   6,    9,    8],
       [  57,    0,   64],
       [  63,   12, 1056]])

In [39]:
p = np.percentile(sales, 90)

In [41]:
p.round(2)

262.4

In [42]:
#unique
np.unique(sales)

array([   0,    6,    8,    9,   12,   57,   63,   64, 1056])

In [47]:
np.sqrt(sales).round(2)

array([[ 2.45,  3.  ,  2.83],
       [ 7.55,  0.  ,  8.  ],
       [ 7.94,  3.46, 32.5 ]])