# Broadcasting

It is a vectorized operations with array of different sizes, where NumPy will expend the smaller array to 'fit' the large one

            Single values (scaler) can be broadcast into arrays of any dimension
            dimensions with a length greater than one must be same size

In [11]:
import numpy as np
x = np.array([[1, 2, 3],
             [1, 2, 3],
             [1, 2, 3]])

In [12]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [13]:
x + 1  # added value one in evenery element of an array x (broadcasting)

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [14]:
y = np.array([[1, 2, 3],
             [1, 2, 3],
             [1, 2, 3]])
y

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
#broadcasting
y + np.array([3, 2, 1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [17]:
y + np.array([3, 2, 1]).reshape(3,1)

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [18]:
y + np.array([2,1])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [19]:
y[0, :] + y[:, 1].reshape(3,1)

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [20]:
np.ones((2,3,3), dtype=int) + np.ones(3, dtype=int)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [24]:
#Element wise Multiplication
a = np.array([5, 8, 9, 3])

b = np.array([6, 12,0, 8])

In [29]:
print(a.shape)

(4,)


In [30]:
print(b.shape)

(4,)


In [32]:
#array are comatible b'coze of same dim.

c = a*b   #broadcasting
c

array([30, 96,  0, 24])

In [33]:
c.shape

(4,)

In [34]:
#Array broadcasting of single dimensional Array
a = np.array([17, 11, 19])

In [35]:
a.shape

(3,)

In [36]:
a

array([17, 11, 19])

In [37]:
b = 3

In [38]:
b

3

In [42]:
c = a + b  #Broadcasting happend, becouse mismatch in array dimension

In [43]:
c

array([20, 14, 22])

In [44]:
#Broadcasting of - 2D Array
a = np.array([[14, 13, 26],
             [16, 25, 40]])
a

array([[14, 13, 26],
       [16, 25, 40]])

In [45]:
a.shape

(2, 3)

In [46]:
b = 4

In [47]:
c = a + b

In [48]:
c

array([[18, 17, 30],
       [20, 29, 44]])

https://www.geeksforgeeks.org/numpy-array-broadcasting/