In [1]:
import numpy as np

- Getting some elements out of an existing array and creating a new array called filtering.

- If the value at an index is True that the element is contained in the filter array, if the value at that index is False that the element is excluded from that filtered array.

- Filtering Array by indexing them with logical test

- Only the array elements in positions where the logical test returns True are returned



In [3]:
sales = [[5, 8, 0, 6, 10],
        [7, 9, 9, 0, 8]]

In [4]:
sales_array = np.array(sales)

In [5]:
sales_array

array([[ 5,  8,  0,  6, 10],
       [ 7,  9,  9,  0,  8]])

In [7]:
sales_array != 0

array([[ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True]])

In [10]:
sales_array[sales_array != 0]

array([ 5,  8,  6, 10,  7,  9,  9,  8])

In [15]:
sales = ([0, 5, 155, 0, 518],
                      [0, 1827, 616, 317, 325])

In [16]:
sales_array = np.array(sales)

In [20]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [17]:
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   0, 616])

In [19]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [21]:
mask = (sales_array > 100) & (sales_array <500)

In [22]:
sales_array[mask]

array([155, 317, 325])

In [23]:
#filter arrays based on values in other array

In [25]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [28]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
newarr

array([41, 43])

In [85]:
#Creating a filter array that return the values higher than 42

import numpy as np

arr = np.array([41, 42, 43, 44])

#create an empty list
filter_arr = []

In [86]:
arr[filter_arr]

array([], dtype=int32)

In [87]:
#go through each element in arr

for element in a:
    #if the element is higher than 42, set the value True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)


In [88]:
new_arr = arr[filter_arr]

In [89]:
print(filter_arr)

[False, False, True, True]


In [90]:
print(new_arr)

[43 44]


In [104]:
#creation of an array return only even element

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
#Creating a empty array
filter_array1 = []

In [111]:
filter_array1

[]

In [114]:
#logial part element is even
for element in arr1:
    if element % 2 == 0:
        filter_array1.append(True)
    else:
        filter_array1.append(False)


In [116]:
filter_array1

[False, True, False, True, False, True, False, True, False, True]

In [120]:
new_arr = arr1[filter_array1]

In [121]:
new_arr

array([ 2,  4,  6,  8, 10])

In [123]:
#Filter Directly from Array

x = np.array([16, 25, 38, 42, 65, 70])

new_arr = x > 42

In [124]:
new_arr

array([False, False, False, False,  True,  True])

In [125]:
my_array = np.arange(20)

In [126]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
my_array[my_array % 2 == 0 ]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [148]:
even_odd = np.array(['even', 'odd'] * 10)
even_odd.reshape(4, 5)

array([['even', 'odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd', 'even'],
       ['odd', 'even', 'odd', 'even', 'odd']], dtype='<U4')

In [149]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [150]:
even_odd[even_odd!= 0]

<ipython-input-150-6d212b788214>:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  even_odd[even_odd!= 0]


array([['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
        'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
        'even', 'odd', 'even', 'odd']], dtype='<U4')