In [3]:
import numpy as np

In [4]:
sales = [0, 258,0, 564, 7, 9, 10, 21, 564, 64]
sales_arry = np.array(sales)
sales


[0, 258, 0, 564, 7, 9, 10, 21, 564, 64]

Key Properties of an Arrays:

- ndim - the nnumber of diensions (axis) in the array
   
- shape - the size of the each dimension

- size - the total numbers of elements in the array

- dtype - the data types of the elements in the array

In [6]:
#types of array

sales = [0, 56, 98, 78, 62, 145, 13]
np_arr = np.array(sales)
np_arr
type(np_arr)

numpy.ndarray

In [9]:
print(f"ndim: {np_arr.ndim}")

ndim: 1


In [13]:
print(f"shape: {np_arr.shape}")

shape: (7,)


In [14]:
print(f"size: {np_arr.shape}")

size: (7,)


In [15]:
print(f"dtype: {np_arr.dtype}")

dtype: int32


In [16]:
#Converting a nested list creates a m-dimensional array
#Note: The nested list must be equal length

sales = [[16, 69, 78], [74, 65, 12]]
n_sales = np.array(sales)

In [17]:
n_sales

array([[16, 69, 78],
       [74, 65, 12]])

In [18]:
type(n_sales)

numpy.ndarray

In [21]:
print(n_sales.ndim)

2


In [22]:
n_sales.shape

(2, 3)

In [23]:
n_sales.dtype

dtype('int32')

In [24]:
n_sales.size

6

In [25]:
np.byte(n_sales)

array([[16, 69, 78],
       [74, 65, 12]], dtype=int8)

In [29]:
a = np.array(range(5))
a

array([0, 1, 2, 3, 4])

In [31]:
a_2d = np.array((range(5), range(5)))

In [32]:
a_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [33]:
a.shape

(5,)

In [34]:
a_2d.shape

(2, 5)

In [35]:
a_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [36]:
a.size

5

In [37]:
a_2d.size

10

In [38]:
a.T

array([0, 1, 2, 3, 4])

In [40]:
a_2d.T   #Transpose

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [42]:
a_2d.T.shape

(5, 2)

In [43]:
a.dtype

dtype('int32')

In [45]:
a_2d.dtype

dtype('int32')

In [47]:
#Assignment1: -

my_list = [x * 10 for x in range(1, 11)]
npy_list = np.array(my_list)
npy_list

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [48]:
npy_list.ndim

1

In [49]:
npy_list.shape

(10,)

In [50]:
npy_list.size

10

In [51]:
npy_list.dtype

dtype('int32')

In [53]:
#reshape
npy_list.reshape(2, 5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [55]:
npy_list.size

10

# Array Creation

In [60]:
#ones
a = np.ones(5)

In [61]:
a

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(25, dtype=int).reshape(5,5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
#Zeros

np.zeros(4)

array([0., 0., 0., 0.])

In [65]:
np.zeros(12, int).reshape(3,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
#Identity

np.identity(3, int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [81]:
np.identity(12).reshape(8, 18)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1.]])

In [82]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [85]:
np.arange(6, 10)

array([6, 7, 8, 9])

In [86]:
np.arange(6, 10).reshape(2,2)

array([[6, 7],
       [8, 9]])

In [93]:
np.linspace(0, 10, 5, dtype=int)

array([ 0,  2,  5,  7, 10])

In [95]:
np.linspace(6, 100, 12, dtype=int).reshape(4,3)

array([[  6,  14,  23],
       [ 31,  40,  48],
       [ 57,  65,  74],
       [ 82,  91, 100]])

# Random Number Arrays

In [101]:
#default rng
from numpy.random import default_rng

#creating a random number generator with a seeds of 12345

rng = default_rng(12345)

ra = rng.random(5)

ra

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955])

In [106]:
#normal random generator

from numpy.random import default_rng


rng = default_rng(12345)
mean, stdev = 5, 1

rn = rng.normal(mean, stdev, size = 5)
rn

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669])

In [108]:
import numpy as np
rng = np.random.default_rng(12345)
rng.random(5)

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955])

In [113]:
import numpy as np
rn = np.random.default_rng(61625)
mean, stdev = 5, 1
rn.normal(5, mean, stdev)

array([5.02959836])

In [115]:
rng.integers(0, 10, 100)

array([1, 6, 5, 2, 5, 0, 0, 6, 1, 7, 8, 3, 8, 0, 8, 6, 1, 4, 9, 6, 5, 2,
       1, 8, 2, 3, 4, 8, 9, 5, 0, 1, 8, 9, 1, 9, 1, 0, 4, 7, 4, 0, 8, 8,
       9, 5, 1, 6, 0, 8, 5, 2, 7, 1, 8, 8, 9, 9, 0, 2, 2, 2, 2, 4, 9, 9,
       8, 0, 0, 0, 3, 2, 0, 6, 2, 9, 0, 4, 3, 3, 2, 4, 0, 9, 9, 1, 2, 1,
       6, 0, 2, 5, 1, 9, 8, 2, 8, 1, 6, 9], dtype=int64)

In [116]:
rn.integers(5, 8, 40)

array([5, 6, 6, 5, 6, 5, 5, 6, 5, 7, 7, 6, 7, 5, 7, 7, 5, 6, 7, 6, 6, 5,
       5, 7, 5, 6, 6, 7, 7, 6, 5, 5, 7, 7, 5, 7, 5, 5, 6, 7], dtype=int64)

In [117]:
rng.normal(50, 5, 10)

array([38.03742588, 55.87749824, 51.77404083, 43.99778752, 52.85943123,
       56.68151281, 50.56723721, 53.47123195, 42.00575304, 37.50963484])

In [133]:
#Assignment 1 - Array Creation

import numpy as np

#create an array

arr = np.linspace(10, 100, 10).reshape(5,2)

In [134]:
arr

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [135]:
from numpy.random import default_rng
rng = default_rng(2022)
rnd_arr = rng.random(9).reshape(3, 3)

In [136]:
rnd_arr

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [139]:
#Assignment 2 - Using arange function for avove Assignent 1

ar = np.arange(10, 101, 10).reshape(5,2)
ar

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [146]:
#Assignmet 3 - Create 3 X 3 random number between 0 and 1? Use a random state of 2022

rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Array Indexing & Slicing - 1 D

- array[index] - indexing to access a single element (o-index)

- array[start, stop, step size] - slicing to access a series of elements (stop is not inclusive)

In [149]:
product_array = ['fruits', 'vegetables', 'cearls', 'Beavrage', 'Non-Vegetable', 'Milk-Dairy']

In [150]:
product_array

['fruits', 'vegetables', 'cearls', 'Beavrage', 'Non-Vegetable', 'Milk-Dairy']

In [152]:
product_array[1]

'vegetables'

In [153]:
product_array[-1]

'Milk-Dairy'

In [154]:
product_array[:5]  #Access first five elements

['fruits', 'vegetables', 'cearls', 'Beavrage', 'Non-Vegetable']

In [156]:
 product_array[2:5] #Acees indexing from 2nd elements to 4th - indexing start from 0-th

['cearls', 'Beavrage', 'Non-Vegetable']

#  Indexing & Slicing - 2 D Array

- array[row index, column index]

- array[start: stop: setp size, start:stop:step size]

In [157]:
product_array2D = ['Spices', 'Dry Fruits', 'Juices', 'fruits', 'vegetables', 'cearls', 'Beavrage', 'Non-Vegetable', 'Milk-Dairy']

In [162]:
product_array2D

['Spices',
 'Dry Fruits',
 'Juices',
 'fruits',
 'vegetables',
 'cearls',
 'Beavrage',
 'Non-Vegetable',
 'Milk-Dairy']

In [164]:
type(product_array2D)

list

In [174]:
a = np.array(product_array2D)

In [175]:
a

array(['Spices', 'Dry Fruits', 'Juices', 'fruits', 'vegetables', 'cearls',
       'Beavrage', 'Non-Vegetable', 'Milk-Dairy'], dtype='<U13')

In [180]:
x = a.reshape(3,3)

In [181]:
x

array([['Spices', 'Dry Fruits', 'Juices'],
       ['fruits', 'vegetables', 'cearls'],
       ['Beavrage', 'Non-Vegetable', 'Milk-Dairy']], dtype='<U13')

In [185]:
x[1, 2]

'cearls'

In [188]:
x[:, 1:]

array([['Dry Fruits', 'Juices'],
       ['vegetables', 'cearls'],
       ['Non-Vegetable', 'Milk-Dairy']], dtype='<U13')

In [189]:
x[1:, :]

array([['fruits', 'vegetables', 'cearls'],
       ['Beavrage', 'Non-Vegetable', 'Milk-Dairy']], dtype='<U13')

In [193]:
int_arr = np.arange(12)

In [194]:
int_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [195]:
int_arr[2]

2

In [196]:
int_arr[-2]

10

In [197]:
int_arr[:5]

array([0, 1, 2, 3, 4])

In [198]:
int_arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [199]:
new_arr = int_arr.reshape(3, 4)

In [200]:
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
new_arr[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [206]:
#Assignment - Accessing Array Data

rng = np.random.default_rng(102)
ra = rng.random(9).reshape(3,3)
ra

array([[0.15999115, 0.58594351, 0.82383678],
       [0.29726024, 0.68489952, 0.46388416],
       [0.89135743, 0.56487326, 0.99319199]])

In [207]:
#Access first 2 rows
ra[2:]

array([[0.89135743, 0.56487326, 0.99319199]])

# Array Operations

In [1]:
import numpy as np

In [7]:
#Arithmetic Operations

sales = [[0, 5, 155, 0, 518],
        [0, 1827, 617, 317, 325]]
sales_arr = np.array(sales)
sales_arr

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  617,  317,  325]])

In [8]:
sales_arr + 2 #added 2 to every elements in the array

array([[   2,    7,  157,    2,  520],
       [   2, 1829,  619,  319,  327]])

In [9]:
quantity = sales_arr[0, :]  #Assign all the elements in the first row to quantity

In [10]:
price = sales_arr[1, :]   #Assign all the elements in the second row to price

quantity * price

array([     0,   9135,  95635,      0, 168350])

In [16]:
import numpy as np

rng =np.random.default_rng(616)
inventory = rng.integers(0, 100, 10)

In [18]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [19]:
inventory - 14  #arithmetic operation Performed

array([25, 25, 79, 72, 34, 32, 34, 16, -3, 43], dtype=int64)

In [21]:
 inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [24]:
price = (rng.random(10)*10).round(1)
price

array([7.8, 9.6, 1.9, 1.7, 4.7, 5.9, 4.3, 8.2, 3.8, 0.2])

In [26]:
price * inventory

array([304.2, 374.4, 176.7, 146.2, 225.6, 271.4, 206.4, 246. ,  41.8,
        11.4])

In [32]:
(price * inventory).sum().round(3)

2004.1

In [33]:
invent_list = list(inventory)

In [34]:
invent_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [36]:
#Assignment: - we’ve gotten the basics down, we can start using NumPy for our first tasks. As part of a promotion, we
#want to apply a random discount to surprise our customers and generate social media buzz.

prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

#First, add a flat shipping cost of 5 to our prices to get the ‘total’ amount owed.
total = prices + 5

In [68]:
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])