where() is used for conditional selection and manipulation of array

  synytax:
        np.where(logical test, value if True, value if false)

In [4]:
import numpy as np
inventory_array = np.array([12, 102, 18, 0, 0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [5]:
product_array = np.array(['fruits', 'vegetables', 'cereals', 'dairy', 'eggs'])

In [6]:
product_array

array(['fruits', 'vegetables', 'cereals', 'dairy', 'eggs'], dtype='<U10')

In [7]:
#if inventory is 0 or negative assign 'Out of Stock', otherwise 'In Stock'

np.where(inventory_array <=0, 'Out of Stock', 'In Stock')

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [8]:
#If inventroy is 0 or -ve assign out of stock otherwise product value
np.where(inventory_array <=0, 'Out of Stock', product_array)

array(['fruits', 'vegetables', 'cereals', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [9]:
aa = np.arange(20)
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
result = np.where(aa > 12)
result

(array([13, 14, 15, 16, 17, 18, 19], dtype=int64),)